### ISSUE TITLE
Usability in case of no specific target domain

### ISSUE THREAD

**Issue by ibrahimsharaf** [hsqmlzno1/HATN#11]
Hi, thank you for releasing your work!

I have a question regarding the model adaptability in a slightly different case, I want to train a generic sentiment classifier on multiple domains (multiple datasets), without having a specific target domain, how would that fit in the current model?

**Comment by hsqmlzno1** [comment]
Sure,  you can just train a multinomial adversarial network as the P-net using multiple domains and another networks for learning domain-specific information.
